version: '3'

env:
  BUNDLE_PATH: .vendor

vars:
  VERSION:
    sh: git describe --tags --dirty --always
  GEM_VERSION:
    sh: ruby -e "puts Gem::Version.new(ARGV[0].split('-')[0] + '-' + ARGV[0].split('-')[1..].join('.'))" {{.VERSION}}
  GEM_NAME: jekyll-rdf
  DOCKER_IMAGE: aksw/jekyll-rdf

tasks:

  default:
    desc: The list of all defined tasks
    cmds:
      - task -a

  info:
    desc: Output some variables
    cmds:
      - |
        echo "VERSION: {{.VERSION}}"
        echo "GEM_VERSION: {{.GEM_VERSION}}"
        echo "GEM_NAME: {{.GEM_NAME}}"
        echo "DOCKER_IMAGE: {{.DOCKER_IMAGE}}"

  install:
    desc: Install jekyll rdf and its dependencies with bundle
    cmds:
      - bundle install

  gem:build:
    desc: Build the ruby gem
    cmds:
      - gem build {{.GEM_NAME}}.gemspec

  gem:push:
    desc: Push the gem to rubygems.org
    cmds:
      - gem push {{.GEM_NAME}}-{{.GEM_VERSION}}.gem

  docker:build:
    desc: The list of all defined tasks
    cmds:
      - docker build --no-cache --build-arg VERSION={{.VERSION}} -t {{.DOCKER_IMAGE}}:{{.VERSION}} .

  test:
    desc: Run the tests
    deps:
      - task: test:setup
    cmds:
      - bundle exec rake test

  test:setup:
    desc: Setup the test environment
    cmds:
      - task: test:setup:endpoint-container
      - |
        cd test/theme-gem
        bundle install
      - bundle install

  test:setup:endpoint-container:
    desc: Start a saprql endpoint for the tests
    cmds:
      - docker run --rm -d -p 3030:3030 --name jekyll_rdf_test_endpoint stain/jena-fuseki:4.8.0 ./fuseki-server --mem /remote
    status:
      - '[ "$( docker inspect --format "{{`{{.State.Running}}`}}" jekyll_rdf_test_endpoint )" = "true" ]'
