name: ci

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git describe
        id: ghd
        uses: proudust/gh-describe@v1
      - name: Check outputs
        run: |
          echo "describe: ${{ steps.ghd.outputs.describe }}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.4.1
        with:
          images: |
            ghcr.io/aksw/jekyll-rdf
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          build-args: VERSION=${{ steps.ghd.outputs.describe }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
